VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
VIALRGB_ENABLE = yes

TAP_DANCE_ENABLE = no
MOUSEKEY_ENABLE = no
KEY_LOCK_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
LTO_ENABLE = yes
